### ISSUE TITLE
“WIP” is wrongly capitalized in badge markup

### ISSUE THREAD

**Issue by roryokane** [jantman/repostatus.org#14]
In the markup files for the “WIP” status, such as [`badges/latest/wip_md.txt`](https://github.com/jantman/repostatus.org/blob/42e2051782cd22de8466c66083cf3f071483bbf0/badges/latest/wip_md.txt), the status name is capitalized as “Wip”. This is bad grammar.

The problem is [this code in the `fabfile.py`](https://github.com/jantman/repostatus.org/blob/42e2051782cd22de8466c66083cf3f071483bbf0/fabfile.py#L64): `badge_name.capitalize()`. To avoid having to special-case the “WIP” status when doing this capitalization, you could instead specify a canonical capitalization for each name in [the JSON](https://github.com/jantman/repostatus.org/blob/42e2051782cd22de8466c66083cf3f071483bbf0/badges/latest/badges.json). The canonical capitalization could be in the main key:

```json
"WIP": {
  "description": "…",
  "url": "…"
}
```

or in a sub-key:

```json
"wip": {
  "description": "…",
  "url": "…",
  "capitalized": "WIP"
}
```

**Comment by jantman** [comment]
Agreed with this, thanks for catching it. Changing the JSON is going to require a version bump, but I'll try to get to it sometime today or tonight.
