### ISSUE TITLE
Propose status of all repos

### ISSUE THREAD

**Issue by mexindian** [jantman/repostatus.org#23]
A biiiiiit beyond my ability level, but it might help uptake if I didn't have to identify badges for all my repos, but instead I got a list of my repos with the appropriate badge selected (or at least a range of possible badges).

Starting from this: **https://developer.github.com/v3/projects/**

we could extract the list of projects, looking in particular at "modified last" date... 
if it's brand new, suggest either concept, wip, or active, 
if it's older than x, then propose either inactive/suspended etc.

We could also look for number of open issues to have more granularity in the estimate?

just a thought.

**Comment by HoverBaum** [comment]
This would be a cool feature if we had a tool to manage the statuses of your repos. I imagine an application that lists your repositories and finds their status and lets you change them. It would then make a new commit to the repo to change the displayed badge. 

I would be totally up to build a thing like that but without it I don't see how and where we could generate a suggestion for people.

On a side note: Do people use the projects feature? I haven't really seen it used all that much.

**Comment by jantman** [comment]
@mexindian @HoverBaum 

I'm going to leave it up to the community for whether or not a tool like this gets created and how it would work. When I first started this project I added badges to all my other repos... I already had clones of all of them on my machine, so it was just a matter of filtering out forks, coming up with a list, manually assigning the statuses, and then a small one-time-use script to inject the badges into the README.

As to status suggestions, I have a relatively strong opinion that trying to accurately determine repository status by machine isn't really feasible. As an example, *I* would say that a "brand new" repo shouldn't even have "active" as a suggestion, and I'd say "active" is more likely for old repos.

About the only thing *I* would see working for a rough guess, is if the contents of the repository is a packaged and versioned piece of software that uses SemVer (i.e. a ruby/python/java/node/etc. package), 1.0.0+ version should be a good indicator of Concept/WIP/Suspended vs the other statuses, and then maybe Active/Inactive/Unsupported could be determined based on the owner's activity on that repo *compared to their activity on their other repos*...

I think the bottom line for me is, if someone wants to write this tool, fine, but it should probably be a separate project...

PS - Apologies for my extended absence, I've been going through some "life events" that have precluded me from putting much work in on my OSS projects. I should be back to work on the issues here in the next few days.

**Comment by mexindian** [comment]
fair enuff... should I close? Oh also, I was thinking, it might be a good tag to have "seeking collaborator". Not 100% down the alley of this, but also not unrelated. Thoughts?

**Comment by jantman** [comment]
I think I'm going to close. If there's more interest from the community and there are further comments, I'll reconsider.

As to "seeking collaborator", I think that's really separate from the overall project status, and there are also some community efforts around that (such as clear notices that point to the contributing docs).
