### ISSUE TITLE
What about shields.io?

### ISSUE THREAD

**Issue by deeplook** [jantman/repostatus.org#32]
What's wrong with using [shields.io](https://shields.io) directly? In the simplest case like this (but there are many more options for colors, logos, styles):

![](https://img.shields.io/badge/repo%20status-active-brightgreen.svg) (https://img.shields.io/badge/repo%20status-active-brightgreen.svg)

**Comment by deeplook** [comment]
I understand, and I assume the advantage is being independent of the language or content of the repository. Like in Python you could use `setup.py` with the appropriate classifiers.

**Comment by jantman** [comment]
Exactly. I'm mainly a Python developer, and the PyPI Trove Classifiers are great for this. But I wanted a solution that would work across all of my repos, which include Python, Ruby, etc. as well as things that aren't even code at all, like documentation or CAD models. Really the only common thread I could find is that most repositories and/or software projects (even long before git) can have some sort of text-based README file, and we can put a "special" string in it...
