### ISSUE TITLE
repostatus.org hard to read

### ISSUE THREAD

**Issue by JoelMon** [jantman/repostatus.org#38]
Hello,

Just wanted to comment that the repostatus.org is using a grayish tiny font on a light background. It makes the site a pain to read.

![image](https://user-images.githubusercontent.com/6587811/122290406-b247ec00-cec1-11eb-8b78-235b7e0dd59b.png)

**Comment by jantman** [comment]
Sorry for the delay. Yeah, you're completely right about that.

I'm about to go on holiday for two weeks, but I'll gladly accept a PR to fix this, or try to tackle it when I get back.

**Comment by JoelMon** [comment]
> Sorry for the delay. Yeah, you're completely right about that.
> 
> I'm about to go on holiday for two weeks, but I'll gladly accept a PR to fix this, or try to tackle it when I get back.

No problem! I'll see if I can look into it. Enjoy your rest!
