### ISSUE TITLE
does repostatus.org still exist?

### ISSUE THREAD

**Issue by jennybc** [jantman/repostatus.org#8]
The repostatus.org server cannot be found.

**Comment by jennybc** [comment]
It seems very important to go to `www.repostatus.org` instead of `repostatus.org`. And the README links to the latter.

**Comment by jantman** [comment]
:( wow, this was a pretty major slip-up on my part.

repostatus.org is hosted out of GitHub Pages... I think all this time I was completely disregarding that my browser (modern Firefox) retries requests with a "www." if a bare-domain request can't be resolved.

Marking this as a bug, I'll hopefully deal with this and the other PRs this week.

**Comment by jantman** [comment]
Also, thanks for this. I'm going to get a contributor list going as well in the official documentation, and will be sure to include you - your comments on this and some of the other issues are definitely appreciated!
